const tools = require('../tools');

module.exports = {
       name: 'kill',
    aliases: ['murder'],
    description: 'kill a user',
    usage: '-kill @user',
    args: true,
    cooldown: 2,
    minArgs: 0,
    maxArgs: 2,
    async execute(message, args) {
        try {
            //use the given text as the target, or your mention if nothing was given
        
            //select a random message from the list...
            const messages = [
               "$author slips bleach into $mention's lemonade.",
        "$mention dies of natural causes.",
        "$mention dies from bad succ.",
        "$mention dies from dabbing too hard.",
        "$mention dies from posting normie memes.",
        "$mention dies from disrespecting wahmen.",
        "$mention dies from watching the emoji movie and enjoying it.",
        "$author hired me to kill you, but I don't want to! $mention",
        "$mention slips on a banana peel and falls down the stairs.",
        "$author murders $mention with an axe.",
        "$author pressed delete. It deleted $mention",
        "$mention dies because they used a bobby pin to lift their eyelashes",
        "$mention dies because they were just too angry.",
        "$mention decided it was a good idea to fight a tiger while smelling like meat. It did not end well.",
        "$mention disappeared from the universe.",
        "$mention drank some toxic soda before it was recalled.",
        "$mention was killed by $author with baby wipes.",
        "$mention dies in a horrible accident, and it was engineered by $author.",
        "$mention dies of starvation.",
        "$author decapitates $mention with a sword.",
        "$author challenges $mention to a fist fight to the death. $mention wins.",
        "Sorry, $author, I don't like killing people.",
        "$mention dies after swallowing a toothpick.",
        "$mention was murdered by $author and everyone knows it, but there is no proof.",
        "$author kills $mention after hours of torture.",
        "$mention dies on death row via lethal injection after murdering $author and their family.",
        "$mention vocally opposed the Clintons and then suddenly disappeared.",
        "$author shoots $mention in the head.",
        "$author, are you sure you want to kill $mention? They seem nice to me.",
        "$mention lives, despite $author's murder attempt.",
        "$mention gets hit by a car.",
        "$mention gets struck by lightning.",
        "$mention reads memes till they die.",
        "$mention dies at the hands of $author.",
        "$mention has some bad chinese food, and pays the ultimate price.",
        "$mention chokes on cheerios and dies. What an idiot...",
        "$mention is killed by their own stupidity.",
        "$mention is killed in a robbery gone wrong.",
        "$mention is dead at the hands of $author.",
        "$mention can't be killed, as they are a ghost.",
        "$mention gets stabbed by $author",
        "In a sudden turn of events, I **don't** kill $mention.",
        "$mention kills themselves after realizing how dumb $author is.",
        "$mention bleeds out after trying to get on \"Dumbest hillbilly moments\".",
        "$mention is not able to be killed. Oh, wait, no, $author kills them anyway.",
        "$author strangles $mention.",
        "After getting pushed into the ocean by $author, $mention is eaten by a shark.",
        "$mention dies.", "After a struggle, $mention kills $author",
        "$mention is abducted by aliens, and the government kills them to cover it up.",
        "$mention got stepped on by an elephant.", "$mention died from eating too much ass.",
        "$mention died from shitting for 36 hours straight.",
        "$mention is so dumb that they choked on oxygen.",
        "$mention died from not eating enough ass.",
        "$mention died from doing the ice bucket challenge.",
        "$mention died from eating too much ass.",
        "The bullet missed Harambe and hit $mention instead. Yay for Harambe!",
        "Aids, $mention died from aids.",
        "$mention died because RemindMeBot forgot to remind them to breathe",
        "$mention died due to eating WAY too many hotdogs in preparation for their date Friday night.",
        "$mention got into a knife fight with the pope. One of them is in hell now.",
        "$mention died from swallowing rocks too fast",
        "$mention accidentally clicked on a popup ad that reads \"Doctors hate us, see the one best trick for dying today!\"",
        "$mention died from ebola.",
        "$mention fell into a pit of angry feminists.",
        "$mention died from drinking too much water Huh, I guess it IS possible!.",
        "$mention died while playing hopscotch on *seemingly* deactivated land mines.",
        "$mention ripped their own heart out to show their love for $author.",
        "$mention died from too many sunburns.",
        "$mention died from a swift kick to the brain.",
        "$mention was eaten alive by ants",
        "$mention died after gaming for 90 hours straight without moving or eating.",
        "$mention tried to outrun a train, the train won.",
        "$mention killed themselves after seeing the normie memes that $author posts.",
        "After raid of roblox kids entered the server, $mention died of cancer.",
        "$mention talked back to mods and got destroyed by the ban hammer.",
        "$mention cums in eye, goes blind, runs for help but ran straight onto train tracks and gets plowed by a train.",
        "$mention bought a fidget spinner and drowned in pussy.",
        "$mention died after trying to out-meme Dank Memer.",
        "$mention died from eating too much bread :/",
        "$mention died an honorable death. Death by snoo snoo.",
        "$mention tried to get famous on YouTube by live-streaming something dumb. Skydiving while chained to a fridge.",
        "$mention was walking normally when out of the corner of their eye they saw someone do a bottle flip and dab causing $mention to have a stroke.",
        "$mention died from eating cactus needles.",
        "$mention died after playing with an edgy razor blade fidget spinner.",
        "$mention died because they started playing with a fidget spinner but they realise its 2016 so you start fapping to the old witch in snow white and obama starts mowing their lawn and they jump out of the window and get ripped to pieces by Obama's lawn mower",
        "$mention ate too many laxatives and drowned in their own shit. Ew.",
        "$mention drowned in their own tears.",
        "$mention died eating expired and infected raw fish with the filthiest rice in the world as sushi while being constantly stabbed in the scrotum with a 9inch nail sharp enough to stab through kevlar. The soy sauce was cat piss.",
        "$mention died of oversucc",
        "$mention accidentally tripped and died while getting up to write their suicide note.",
        "$mention died from whacking it too much. (There's a healthy balance, boys)",
        "$mention died from not whacking it enough. (There's a healthy balance, boys)",
        "$author kills $mention with their own foot.",
        "$mention dies due to lack of friends.",
        "$mention chokes on a chicken bone.",
        "$mention went on a ride with a lead balloon.",
        "$mention did not make a meme dank enough and was stoned.",
        "Our lord and savior Gaben strikes $mention with a lighting bolt.",
        "$author tries to shoot the broad side of a barn, misses and hits $mention instead.",
        "$mention slipped in the bathroom and choked on the shower curtain.",
        "While performing colonoscopy on an elephant, $mention gets their head stuck in the elephants rectum and chokes.",
        "$author attempted to play a flute, exploding the head of $mention.",
        "$author straps $mention to an ICBM and sends them to North Korea along with it.",
        "$author drowns $mention in a beer barrel.",
        "$mention was thrown in the crusher of a trash truck by $author.",
        "$mention dropped a Nokia phone on their face and split their skull.",
        "$author cleaves the head of $mention with a keyboard.",
        "$author crushes $mention with a fridge.",
        "$mention chokes in a trash can.",
        "$author fires a supersonic frozen turkey at $mention, killing them instantly.",
        "$mention watched the Emoji Movie and died of sheer cringe.",
        "$author shoots in $mention mouth with rainbow laser, causing $mention head to explode with rainbows and $mention is reborn as unicorn. :unicorn:",
        "$mention ate a piece of exotic butter. It was so amazing that it killed them.",
        "$mention is stuffed into a suit by Freddy on their night guard duty. Oh, not those animatronics again!",
        "$author grabs $mention and shoves them into an auto-freeze machine with some juice and sets the temperature to 100 Kelvin, creating human ice pops.",
        "$author drowns $mention in a tub of hot chocolate. *How was your last drink?*",
        "$mention screams in terror as they accidentally spawn in the cthulhu while uttering random latin words. Cthulhu grabs $mention by the right leg and takes them to his dimension yelling, \"Honey, Dinner's ready!\"",
        "$author feeds toothpaste-filled oreos to $mention, who were apparently allergic to fluorine. GGWP.",
        "$author forgot to zombie-proof $mention lawn... Looks like zombies had a feast last night.",
        "$mention cranks up the music system only to realize the volume was at max and the song playing was Baby by Justin Beiber...",
        "$mention presses a random button and is teleported to the height of 100m, allowing them to fall to their inevitable death. Moral of the story: Don't go around pressing random buttons.",
        "$mention is injected with chocolate syrup, which mutates them into a person made out of chocolate. While doing a part-time job at the Daycare, they are devoured by the hungry babies. :chocolate_bar:",
        "$mention is sucked into Minecraft. $mention, being a noob at the so called Real-Life Minecraft faces the Game Over screen.",
        "$author turns on Goosebumps(2015 film) on the TV. $mention being a scaredy-cat, dies of an heart attack.",
        "$author after a long day, plops down on the couch with $mention and turns on The Big Bang Theory. After a Sheldon Cooper joke, $mention laughs uncontrollably as they die.",
        "$mention was given a chance to synthesize element 119 (Ununennium) and have it named after them, but they messed up. R.I.P.",
        "$author gets $mention to watch anime with them. $mention couldn't handle it.",
        "$mention tried to get crafty, but they accidentally cut themselves with the scissors.:scissors:",
        "$mention goes genocide and Sans totally dunks $mention!",
        "$author was so swag that $mention died due to it. #Swag",
        "$mention has been found guilty, time for their execution!",
        "$mention fell down a cliff while playing Pokemon Go. Good job on keeping your nose in that puny phone. :iphone:",
        "$author strikes $mention with the killing curse... *Avada Kedavra!*",
        "$mention ate an apple and turned out it was made out of wax. Someone died from wax poisoning later that day.",
        "$mention was teleported to the timeline where Jurassic World was real and they were eaten alive by the Indominus Rex.",
        "$mention was charging their Samsung Galaxy Note 7...",
        "$author shot $mention using the Starkiller Base!",
        "$mention was a resident of Alderaan before Darth Vader destroyed the planet...",
        "$mention was scooped by $author and their innards are now Ennard.",
        "$author Alt+F4'd $mention.exe!",
        "$mention was accused of stealing Neptune's crown...",
        "$author eviscerates $mention with a rusty butter knife. Ouch!",
        "$author pushes $mention into the cold vacuum of space.",
        "$author runs $mention over with a PT Cruiser.",
        "$mention trips over his own shoe laces and dies.",
        "$mention tried to pick out the holy grail. He chose... poorly.",
        "$author hulk smashes $mention into a pulp.",
        "$mention steps on a george foreman and dies of waffle foot.",
        "$mention dies from just being a bad, un-likeable dude.",
        "Calling upon the divine powers, $author smites $mention and their heathen ways",
        "$mention has a stroke after a sad miserable existence. They are then devoured by their ample cats.",
        "$mention takes an arrow to the knee. And everywhere else.",
        "$mention dies of dysentery.",
        "$mention dies of AIDS.",
        "$author killed $mention by ripping the skin off of their face and making a mask out of it.",
        "$mention spins a fidget spinner and when it stops he dies...",
        "$mention ripped his heart out..",
        "$author fell in love with $mention then broke his heart literally.",
        "$author blew his ear drums out listening to music too hard.",
        "$author hugs $mention too hard..",
        "$author tears off $mentions lips after a kiss.",
        "$author drags $mentions ears too hard and rips them off.",
        "$mention tried to play in the street...",
        "$mention is killed by a rabbit with a vicious streak a mile wide",
        "$author forgot to leave the car door window open and $mention dies from overheating",
        "$mention dies, but don't let this distract you from the fact that in 1998, The Undertaker threw Mankind off Hell In A Cell, and plummeted 16 ft through an announcer’s table",
        "$mention tips his fedora too far and falls onto the tracks of an oncoming subway.",
        "$mention eats too much copypasta and explodes",
        "$author kills $mention with kindness",
        "no u",
        "$author kills $mention with a candlestick in the study",
        "$mention dies north of the wall and transforms into a white walker",
        "$author thicc and collapses $mention's rib cage",
        "$mention loses the will to live",
        "$mention dies from dabbing too hard",
        "$mention died from a tragic amount of bad succ",
        "$mention dies by swearing on a Christian Minecraft server",
        "$mention died. OOF",
        "$mention died while listening to 'It's every day bro'",
        "$mention died while trying to find the city of England",
        "$mention died from a high salt intake",
        "$mention died due to $author being so stupid",
        "$mention died from reposting in the wrong neighborhood",
        "$mention died when testing a hydrogen bomb. There is nothing left to bury.",
        "$mention died from meme underdose :/",
        "$mention died after realizing how shitty their grammar was",
        "$mention died after fapping 50 times in a row with no break.",
        "$mention dies from severe dislike of sand. It's coarse and rough and irritating it gets everywhere"
                //add your own messages here or suggest them: https://discord.gg/bRTPbpg
            ]
            const killMsg = messages[Math.floor(Math.random() * messages.length)];

            //create an embed for the kill message
            const embed = tools.makeEmbed('', '')
            .setDescription(killMsg);
            tools.sendEmbed(message.channel, embed);
        } catch (err) {
            return tools.errorMessage(message, err);
        }
    },
};
